/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#ifndef __PSOCAPI_H
#define __PSOCAPI_H

#include "I2CHW_1Mstr.h"
#include "I2CHW_1Common.h"
#include "UART_1.h"

#endif
