/******************************************************************************
*  Generated by PSoC Designer 5.0.1127.0
******************************************************************************/
#include <m8c.h>
// I2CHW_1SDA address and mask defines
#pragma	ioport	I2CHW_1SDA_Data_ADDR:	0x4
BYTE			I2CHW_1SDA_Data_ADDR;
#pragma	ioport	I2CHW_1SDA_DriveMode_0_ADDR:	0x104
BYTE			I2CHW_1SDA_DriveMode_0_ADDR;
#pragma	ioport	I2CHW_1SDA_DriveMode_1_ADDR:	0x105
BYTE			I2CHW_1SDA_DriveMode_1_ADDR;
#pragma	ioport	I2CHW_1SDA_DriveMode_2_ADDR:	0x7
BYTE			I2CHW_1SDA_DriveMode_2_ADDR;
#pragma	ioport	I2CHW_1SDA_GlobalSelect_ADDR:	0x6
BYTE			I2CHW_1SDA_GlobalSelect_ADDR;
#pragma	ioport	I2CHW_1SDA_IntCtrl_0_ADDR:	0x106
BYTE			I2CHW_1SDA_IntCtrl_0_ADDR;
#pragma	ioport	I2CHW_1SDA_IntCtrl_1_ADDR:	0x107
BYTE			I2CHW_1SDA_IntCtrl_1_ADDR;
#pragma	ioport	I2CHW_1SDA_IntEn_ADDR:	0x5
BYTE			I2CHW_1SDA_IntEn_ADDR;
#define I2CHW_1SDA_MASK 0x20
// I2CHW_1SCL address and mask defines
#pragma	ioport	I2CHW_1SCL_Data_ADDR:	0x4
BYTE			I2CHW_1SCL_Data_ADDR;
#pragma	ioport	I2CHW_1SCL_DriveMode_0_ADDR:	0x104
BYTE			I2CHW_1SCL_DriveMode_0_ADDR;
#pragma	ioport	I2CHW_1SCL_DriveMode_1_ADDR:	0x105
BYTE			I2CHW_1SCL_DriveMode_1_ADDR;
#pragma	ioport	I2CHW_1SCL_DriveMode_2_ADDR:	0x7
BYTE			I2CHW_1SCL_DriveMode_2_ADDR;
#pragma	ioport	I2CHW_1SCL_GlobalSelect_ADDR:	0x6
BYTE			I2CHW_1SCL_GlobalSelect_ADDR;
#pragma	ioport	I2CHW_1SCL_IntCtrl_0_ADDR:	0x106
BYTE			I2CHW_1SCL_IntCtrl_0_ADDR;
#pragma	ioport	I2CHW_1SCL_IntCtrl_1_ADDR:	0x107
BYTE			I2CHW_1SCL_IntCtrl_1_ADDR;
#pragma	ioport	I2CHW_1SCL_IntEn_ADDR:	0x5
BYTE			I2CHW_1SCL_IntEn_ADDR;
#define I2CHW_1SCL_MASK 0x80
// LED address and mask defines
#pragma	ioport	LED_Data_ADDR:	0x8
BYTE			LED_Data_ADDR;
#pragma	ioport	LED_DriveMode_0_ADDR:	0x108
BYTE			LED_DriveMode_0_ADDR;
#pragma	ioport	LED_DriveMode_1_ADDR:	0x109
BYTE			LED_DriveMode_1_ADDR;
#pragma	ioport	LED_DriveMode_2_ADDR:	0xb
BYTE			LED_DriveMode_2_ADDR;
#pragma	ioport	LED_GlobalSelect_ADDR:	0xa
BYTE			LED_GlobalSelect_ADDR;
#pragma	ioport	LED_IntCtrl_0_ADDR:	0x10a
BYTE			LED_IntCtrl_0_ADDR;
#pragma	ioport	LED_IntCtrl_1_ADDR:	0x10b
BYTE			LED_IntCtrl_1_ADDR;
#pragma	ioport	LED_IntEn_ADDR:	0x9
BYTE			LED_IntEn_ADDR;
#define LED_MASK 0x1
